JobReadyUtube/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobReadyUtube.Models;
using JobReadyUtube.ViewModels;
using System.Data.Entity;

namespace JobReadyUtube.Controllers
{
    public class VideoController : Controller
    {
        // GET: Video
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult UploadVideo()
        {
            using (var db = new MyUtubeDatabaseEntities())
            {
                //TODO find all channel of current user
                //ToDO add to ViewBag.ChannelList
                // go to the view
                var allChannel =
                    db.Channels.Where(x => x.UserId == CurrentSession.CurrentUser.Id).ToList();
                ViewBag.ChannelList = allChannel;
                return View();
            }
        }
        [HttpPost]
        public ActionResult CreateNewChannel(ChannelViewModel model)
        {
            using (var db = new MyUtubeDatabaseEntities())
            {
                var newChannel = new Channel
                {
                    Name = model.ChannelName,
                    Description = model.ChannelDescription,
                    UserId = CurrentSession.CurrentUser.Id

                };
                db.Channels.Add(newChannel);
                db.SaveChanges();
                return Json(new
                {
                    Success = true,
                    ChannelId = newChannel.Id,
                    ChannelName = newChannel.Name
                });
            }
        }

        [HttpPost]
        public ActionResult UploadVideo(VideoViewModel model)
        {
            using (var db = new MyUtubeDatabaseEntities())
            {
                var newVideo = new Video
                {
                    Name = model.VideoName,
                    Description = model.VideoDescription,
                    URL = model.VideoUrl,
                    ChannelId = model.ChannelDropDown,
                    UserId = CurrentSession.CurrentUser.Id,
                    CreatedOn = DateTime.Now,
                    CreatedBy = CurrentSession.CurrentUser.Id,
                    IsActive = true
                };
                db.Videos.Add(newVideo);
                db.SaveChanges();
                return Json(new { Success = true, VideoId = newVideo.Id });
            }
        }

        public ActionResult VideoManagement()
        {
            using (var db = new MyUtubeDatabaseEntities())
            {
                var allVideo = db.Videos.Include(x => x.Channel)
                                        .Where(x => x.UserId == CurrentSession.CurrentUser.Id).ToList();

                return View(allVideo);

            }
        }

        public ActionResult DisplayVideo(int id)
        {
            using (var db = new MyUtubeDatabaseEntities())
            {
                var video = db.Videos.Find(id);
                return View(video);
            }
        }

        public ActionResult AddComment(int videoId, string comment)
        {
            using (var db = new MyUtubeDatabaseEntities())
            {
                var commentObj = new Comment
                {
                    Content = comment,
                    VideoId = videoId,
                    UserId = CurrentSession.CurrentUser.Id,
                    //Cr = CurrentSession.CurrentUser.Id,
                    //CreatedOn = DateTime.Now,
                    //IsActive = true,
                };
                db.Comments.Add(commentObj);
                db.SaveChanges();
                return Json(new { Success = true });
            }
        }

        public ActionResult LoadVideoComment(int videoId)
        {
            using (var db = new MyUtubeDatabaseEntities())
            {
                var allComments = db.Comments.Where(x => x.VideoId == videoId).ToList();
                return PartialView("CommentListPartial", allComments);
            }
        }
    }
}

JobReadyUtube/Views/Shared/_Layout.cshtml
@using JobReadyUtube.ViewModels
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Utube Apps", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Manage Video", "VideoManagement", "Video")</li>
                        <li>@Html.ActionLink("Upload Video", "UploadVideo", "Video")</li>
                        <li><a href="#">Hi @CurrentSession.CurrentUser.Username</a></li>
                        <li>@Html.ActionLink("Logoff", "Logoff", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                        <li>@Html.ActionLink("Register", "Register", "Account")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

   
    @RenderSection("scripts", required: false)
</body>
</html>